# Generated by Django 4.1.4 on 2022-12-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_allcheck_delete_allproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcheck',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='allcheck',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
