# Generated by Django 4.1.4 on 2022-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_allcheck_image_alter_allcheck_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcheck',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
