# Generated by Django 4.1.4 on 2022-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_allcheck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcheck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
