# Generated by Django 4.1.4 on 2022-12-18 13:25

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_allcheck_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcheck',
            old_name='time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='allcheck',
            name='day',
            field=models.CharField(default=builtins.input, max_length=100),
            preserve_default=False,
        ),
    ]
