# Generated by Django 4.1.4 on 2022-12-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_time_allcheck_date_allcheck_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcheck',
            name='online_account',
            field=models.BooleanField(default=False),
        ),
    ]
