# Generated by Django 4.1.4 on 2022-12-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_allcheck_online_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcheck',
            old_name='online_account',
            new_name='status',
        ),
    ]
